version: '3.1'
services:
  gb-postgres:
    container_name: 'gb-postgres'
    image: 'postgres:14'
    volumes: 
      - './docker/database:/var/lib/postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: gbuser
      POSTGRES_PASSWORD: gbpassword
      POSTGRES_DB: gb
    
        